version: 2
updates:
  # master branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "master"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/util/exampleDbServer/node/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(nodedb):"
    target-branch: "master"
    allow:
      - dependency-type: "direct"

  # v2 branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "v2"
    labels:
      - "dependencies"
      - "target:v2"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "discord.js"
      - dependency-name: "discord-api-types"
      - dependency-name: "@discordjs/builders"
