name: Patch Release
on:
  workflow_dispatch:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16.x'
      
      - name: Bump package version
        id: bump-version
        run: echo "::set-output name=VERSION::$(npm version patch --git-tag-version false)"
        
      - name: Check updated version
        run: echo $VERSION
        env:
          VERSION: ${{ steps.bump-version.outputs.VERSION }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "Bump: package version to ${{ steps.bump-version.outputs.VERSION }}"
          committer: github-actions <github-actions@github.com>
          author: github-actions <github-actions@github.com>
          signoff: false
          branch: "bump/package/${{ steps.bump-version.outputs.VERSION }}"
          labels: chore
          delete-branch: true
          title: "Bump: package version to ${{ steps.bump-version.outputs.VERSION }}"
