name: Release Notification

on:
  release:
    types:
      - published
  
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '16.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      
      - name: Check npm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
        
      - name: Run notification
        run: node util/notification
        env:
          TOKEN: ${{ secrets.Y_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
