name: Release Notification

on:
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || !github.event.release.prerelease }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Check npm cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-20.x-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-20.x-
            npm-

      - name: Install dependencies
        run: npm ci

      - name: Run notification
        run: node util/notification
        env:
          TOKEN: ${{ secrets.Y_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
