name: CI

on:
  push:
    branches: 
      - master
    paths-ignore:
      - .env.sample
      - .gitignore
      - .replit
      - config.json.sample
      - LICENSE
      - README.md
      - .github/**
      - .vscode/**
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install
        
      - name: List dependencies
        run: npm list --all
        continue-on-error: true

      - name: Lint
        run: npm run lint -- --max-warnings 0
      
      - name: Compile TypeScript
        run: npm run build

      - name: Test
        run: npm test
