name: CI

on:
  push:
    branches: 
      - master
    paths-ignore:
      - .env.sample
      - .gitignore
      - .replit
      - config.json.sample
      - LICENSE
      - README.md
      - .github/**
      - .vscode/**
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '16.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Check npm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
        
      - name: List dependencies
        run: npm list --all
        continue-on-error: true

      - name: Lint
        run: npm run lint -- --max-warnings 0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '16.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Check npm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        node-version:
          - '12.x'
          - '14.x'
          - '16.x'
    steps:
      - uses: actions/checkout@v3

      - name: Setup config for test
        run: cp util/config-for-test.json config.json
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Check npm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Test to load scripts to Node.js
        run: node -r ./dist/lib -e 'process.exit()'
        
  docs:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '16.x'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Check npm cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci
        
      - name: Setup config for test
        run: cp util/config-for-test.json config.json
        
      - name: Build document
        run: |
          npm run build
          npm run generatecommandlist
      
      - name: Check if there are changes
        run: git diff -w --exit-code

  success-all-test:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - docs
    steps:
      - run: echo "All done"
